#!/bin/bash
mv bilinint*.so bilinint.so
mv mm_bilinint*.so mm_bilinint.so
mv chisq*.so chisq.so
mv deramp*.so deramp.so
mv ellke*.so ellke.so
mv ellpic_bulirsch*.so ellpic_bulirsch.so
mv expramp*.so expramp.so
mv fallingexp*.so fallingexp.so
mv felramp*.so felramp.so
mv linramp*.so linramp.so
mv llramp*.so llramp.so
mv log4qramp*.so log4qramp.so
mv logramp*.so logramp.so
mv lqramp*.so lqramp.so
mv mandelecl*.so mandelecl.so
mv mandeltr*.so mandeltr.so
mv mmbilinint*.so mmbilinint.so
mv nnint*.so nnint.so
mv occultquad*.so occultquad.so
mv quadip*.so quadip.so
mv quadramp*.so quadramp.so
mv re2ramp*.so re2ramp.so
mv relramp*.so relramp.so
mv reqramp*.so reqramp.so
mv risingexp*.so risingexp.so
mv rotation*.so rotation.so
mv rsky*.so rsky.so
mv se2ramp*.so se2ramp.so
mv selramp*.so selramp.so
mv seqramp*.so seqramp.so
mv seramp*.so seramp.so
mv sincos2*.so sincos2.so
mv trnlldsp*.so trnlldsp.so
mv vsll*.so vsll.so
