name: eureka
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.9.7
    - astropy
    - batman-package
    - bokeh[version='<3.0']
    - ccdproc
    - celerite # Needed for GP
    - corner
    - dynesty[version='>1.0'] # Lower limit needed for specific arguments
    - emcee[version='>3.0.0'] # Lower limit needed for specific arguments
    - flake8 # Needed for testing
    - george # Needed for GP
    - h5py
    - ipykernel
    - ipython
    - jupyter
    - lmfit
    - matplotlib[version='>=3.6'] # Lower limit needed for set_layout_engine()
    - nbsphinx # Needed for documentation
    - numpy[version='>=1.20.0,<=1.23'] # Upper limit needed for Apple silicon
    - numpydoc # Needed for documentation
    - pandas
    - photutils
    - pip # required for the pip installs below
    - pytest # Needed for testing
    - pytest-cov # Needed for testing
    - pytest-doctestplus # Needed for testing
    - requests
    - scipy[version='>=1.4.0'] # Lower limit needed for scipy.fft
    - sphinx # Needed for documentation
    - sphinx-automodapi # Needed for documentation
    - tqdm
    - pip:
        - astraeus@git+https://github.com/kevin218/Astraeus@main
        - crds
        - exotic-ld
        - image_registration@git+https://github.com/keflavich/image_registration@master # Need GitHub version to avoid np.float issue
        - jwst==1.11.4
        - myst-parser # Needed for documentation
        - setuptools_scm # Needed for version number
        - sphinx-rtd-theme # Needed for documentation
        - stcal>=1.0.0 # Lower limit needed for our create_integration_model function
        - stdatamodels
        - svo_filters
