name: Pytest Testing

on:
  push:
    branches:
      - main
      - "releases/**"

permissions:
  contents: read

jobs:
  pytest:
    uses: ./.github/workflows/reusable-pytest.yml
    with:
      upload-codecov: true
    secrets: inherit
